### ISSUE TITLE
WasmGC detection not working in Chrome 119

### ISSUE THREAD

**Issue by rocketraman** [GoogleChromeLabs/wasm-feature-detect#73]
Chrome 119 has WasmGC enabled by default, but your browser at https://webassembly.org/roadmap/ still shows it as "not supported".

**Comment by tomayac** [comment]
Not a problem with the library, see the screenshot showing GC being supported:

![Screenshot 2023-11-02 at 13 17 15](https://github.com/GoogleChromeLabs/wasm-feature-detect/assets/145676/a8627664-5393-4d46-9f81-953bfcc849fc)

I will open a PR on the Wasm page so that it uses the latest version of the library, which is the actual problem. Thanks for reporting nonetheless.

**Comment by tomayac** [comment]
The website PR: https://github.com/WebAssembly/website/pull/353.
